Added button to extend session and changed styles of the timer
Swiatlon/University-FN pull request #58
Opened 2024-11-23 12:36 UTC by Svvida

2024-11-23 16:06 UTC, Swiatlon requested changes

2024-11-23 16:06 UTC, Swiatlon commented on src/components/shared/appBar/elements/AppBarTimer.tsx
> +      const formattedTime = `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
Ustawiłbym zmienne koło siebie a funkcje też koło siebie

2024-11-23 16:06 UTC, Swiatlon commented on src/components/shared/appBar/elements/AppBarTimer.tsx
> +    <Box display="flex" alignItems="center" sx={{ lineHeight: 1 }}>
Strasznie dużo stylów css, zerkniemy na to razem

2024-11-23 16:06 UTC, Swiatlon commented on src/components/shared/appBar/elements/AppBarExtSessionIcon.tsx
> +    const sessionID = sessionStorage.getItem('sessionUUID');
enter

2024-11-23 16:06 UTC, Swiatlon commented on src/components/shared/appBar/elements/AppBarExtSessionIcon.tsx
> +  const iconColor = useMemo(() => {
??

2024-11-23 16:06 UTC, Swiatlon commented on src/components/shared/appBar/elements/AppBarExtSessionIcon.tsx
> +          {isLoading ? <CircularProgress size={24} /> : <RefreshIcon sx={{ color: iconColor, fontSize: '24px' }} />}
raczej staramy się używać wielkości ikonek zamiast stricte fontSize. Chyba że w tym przypadku żadna z nich nie pasuje

2024-11-24 15:35 UTC, Svvida commented on src/components/shared/appBar/elements/AppBarTimer.tsx
> +  deadline: { color: '#f70000', icon: <ErrorOutline sx={{ color: '#f70000', marginRight: 1 }} /> },
Może kiedyś ale nie dziś

2024-11-24 16:01 UTC, Swiatlon approved these changes

2024-11-24 16:02 UTC, merged